import { sql } from "drizzle-orm";
import {
  boolean,
  date,
  index,
  integer,
  jsonb,
  numeric,
  pgSchema,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { agents } from "../agents.js";
import { companies } from "../companies.js";
import { costEvents } from "../cost_events.js";
import { heartbeatRuns } from "../heartbeat_runs.js";
import { issues } from "../issues.js";
import { pluginJobRuns } from "../plugin_jobs.js";
import { projects } from "../projects.js";

const seoOps = pgSchema("seo_ops");

type JsonRecord = Record<string, unknown>;

export const seoOpsSites = seoOps.table(
  "sites",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    domain: text("domain").notNull(),
    canonicalHost: text("canonical_host"),
    defaultUrlScheme: text("default_url_scheme").notNull().default("https"),
    gscSiteUrl: text("gsc_site_url"),
    bingSiteUrl: text("bing_site_url"),
    status: text("status").notNull().default("active"),
    metadata: jsonb("metadata").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyDomainUq: uniqueIndex("seo_ops_sites_company_domain_uq").on(table.companyId, table.domain),
    companyStatusIdx: index("seo_ops_sites_company_status_idx").on(table.companyId, table.status),
  }),
);

export const seoOpsProjectScopes = seoOps.table(
  "project_scopes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    domain: text("domain").notNull(),
    siteScopePrefix: text("site_scope_prefix"),
    includePathPatterns: jsonb("include_path_patterns").$type<string[]>().notNull().default([]),
    excludePathPatterns: jsonb("exclude_path_patterns").$type<string[]>().notNull().default([]),
    languageCode: text("language_code").notNull(),
    locationCode: text("location_code").notNull(),
    deviceContext: text("device_context").notNull().default("desktop"),
    pageTypeFilter: text("page_type_filter"),
    ownershipMode: text("ownership_mode").notNull().default("owned"),
    conflictPolicy: text("conflict_policy").notNull().default("flag_conflict"),
    priority: integer("priority").notNull().default(100),
    status: text("status").notNull().default("active"),
    settings: jsonb("settings").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectStatusIdx: index("seo_ops_project_scopes_company_project_status_idx").on(
      table.companyId,
      table.projectId,
      table.status,
    ),
    companySiteStatusPriorityIdx: index("seo_ops_project_scopes_company_site_status_priority_idx").on(
      table.companyId,
      table.siteId,
      table.status,
      table.priority,
    ),
  }),
);

export const seoOpsDiscoveryRuns = seoOps.table(
  "discovery_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    source: text("source").notNull(),
    status: text("status").notNull().default("running"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
    input: jsonb("input").$type<JsonRecord>().notNull().default({}),
    summary: jsonb("summary").$type<JsonRecord>().notNull().default({}),
    error: text("error"),
    pluginJobRunId: uuid("plugin_job_run_id").references(() => pluginJobRuns.id),
    heartbeatRunId: uuid("heartbeat_run_id").references(() => heartbeatRuns.id),
    costEventId: uuid("cost_event_id").references(() => costEvents.id),
  },
  (table) => ({
    companySourceStartedIdx: index("seo_ops_discovery_runs_company_source_started_idx").on(
      table.companyId,
      table.source,
      table.startedAt,
    ),
    companySiteStartedIdx: index("seo_ops_discovery_runs_company_site_started_idx").on(
      table.companyId,
      table.siteId,
      table.startedAt,
    ),
  }),
);

export const seoOpsPages = seoOps.table(
  "pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    canonicalUrl: text("canonical_url").notNull(),
    canonicalUrlNormalized: text("canonical_url_normalized").notNull(),
    path: text("path").notNull(),
    urlHash: text("url_hash").notNull(),
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    lastDiscoveryRunId: uuid("last_discovery_run_id").references(() => seoOpsDiscoveryRuns.id),
    discoveryStatus: text("discovery_status").notNull().default("seen"),
    discoverySources: jsonb("discovery_sources").$type<string[]>().notNull().default([]),
    sitemapLastmod: timestamp("sitemap_lastmod", { withTimezone: true }),
    httpStatus: integer("http_status"),
    redirectTargetUrl: text("redirect_target_url"),
    declaredCanonicalUrl: text("declared_canonical_url"),
    robotsStatus: text("robots_status"),
    indexabilityStatus: text("indexability_status"),
    title: text("title"),
    h1: text("h1"),
    metaDescription: text("meta_description"),
    detectedLanguageCode: text("detected_language_code"),
    schemaTypes: jsonb("schema_types").$type<string[]>().notNull().default([]),
    pageType: text("page_type"),
    contentHash: text("content_hash"),
    enrichment: jsonb("enrichment").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companySiteCanonicalUq: uniqueIndex("seo_ops_pages_company_site_canonical_uq").on(
      table.companyId,
      table.siteId,
      table.canonicalUrlNormalized,
    ),
    companySiteUrlHashUq: uniqueIndex("seo_ops_pages_company_site_url_hash_uq").on(
      table.companyId,
      table.siteId,
      table.urlHash,
    ),
    companySiteLastSeenIdx: index("seo_ops_pages_company_site_last_seen_idx").on(
      table.companyId,
      table.siteId,
      table.lastSeenAt,
    ),
    companySiteDiscoveryStatusIdx: index("seo_ops_pages_company_site_discovery_status_idx").on(
      table.companyId,
      table.siteId,
      table.discoveryStatus,
    ),
  }),
);

export const seoOpsProjectPages = seoOps.table(
  "project_pages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    pageId: uuid("page_id").notNull().references(() => seoOpsPages.id),
    projectScopeId: uuid("project_scope_id").references(() => seoOpsProjectScopes.id),
    ownershipStatus: text("ownership_status").notNull().default("candidate"),
    ownershipMode: text("ownership_mode").notNull().default("owned"),
    primaryPageType: text("primary_page_type"),
    seoState: text("seo_state").notNull().default("new"),
    priority: integer("priority").notNull().default(100),
    monitoringStatus: text("monitoring_status").notNull().default("active"),
    firstOwnedAt: timestamp("first_owned_at", { withTimezone: true }),
    lastEvaluatedAt: timestamp("last_evaluated_at", { withTimezone: true }),
    lastChangedAt: timestamp("last_changed_at", { withTimezone: true }),
    settings: jsonb("settings").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectPageUq: uniqueIndex("seo_ops_project_pages_company_project_page_uq").on(
      table.companyId,
      table.projectId,
      table.pageId,
    ),
    companyProjectMonitoringIdx: index("seo_ops_project_pages_company_project_monitoring_idx").on(
      table.companyId,
      table.projectId,
      table.monitoringStatus,
      table.seoState,
    ),
    companySitePageIdx: index("seo_ops_project_pages_company_site_page_idx").on(
      table.companyId,
      table.siteId,
      table.pageId,
    ),
  }),
);

export const seoOpsKeywords = seoOps.table(
  "keywords",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    normalizedKeyword: text("normalized_keyword").notNull(),
    displayKeyword: text("display_keyword").notNull(),
    languageCode: text("language_code").notNull(),
    locationCode: text("location_code").notNull(),
    deviceContext: text("device_context").notNull().default("desktop"),
    keywordHash: text("keyword_hash").notNull(),
    status: text("status").notNull().default("candidate"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_keywords_identity_uq").on(
      table.normalizedKeyword,
      table.languageCode,
      table.locationCode,
      table.deviceContext,
    ),
    hashUq: uniqueIndex("seo_ops_keywords_hash_uq").on(table.keywordHash),
    localeStatusIdx: index("seo_ops_keywords_locale_status_idx").on(
      table.languageCode,
      table.locationCode,
      table.status,
    ),
  }),
);

export const seoOpsKeywordObservations = seoOps.table(
  "keyword_observations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    pageId: uuid("page_id").references(() => seoOpsPages.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    rawQuery: text("raw_query"),
    normalizedQuery: text("normalized_query"),
    source: text("source").notNull(),
    sourceRunId: text("source_run_id"),
    discoveryRunId: uuid("discovery_run_id").references(() => seoOpsDiscoveryRuns.id),
    dateFrom: date("date_from"),
    dateTo: date("date_to"),
    country: text("country"),
    device: text("device"),
    searchAppearance: text("search_appearance"),
    clicks: integer("clicks"),
    impressions: integer("impressions"),
    ctr: numeric("ctr"),
    averagePosition: numeric("average_position"),
    geoSearchVolume: integer("geo_search_volume"),
    globalSearchVolume: integer("global_search_volume"),
    globalSearchVolumeStatus: text("global_search_volume_status"),
    intentLabel: text("intent_label"),
    intentProbability: numeric("intent_probability"),
    membership: text("membership"),
    reason: text("reason"),
    evidenceStatus: text("evidence_status").notNull().default("raw"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectObservedIdx: index("seo_ops_keyword_observations_company_project_observed_idx").on(
      table.companyId,
      table.projectId,
      table.observedAt,
    ),
    companyProjectPageObservedIdx: index("seo_ops_keyword_observations_company_project_page_observed_idx").on(
      table.companyId,
      table.projectPageId,
      table.observedAt,
    ),
    companyKeywordSourceObservedIdx: index("seo_ops_keyword_observations_company_keyword_source_observed_idx").on(
      table.companyId,
      table.keywordId,
      table.source,
      table.observedAt,
    ),
    gscDedupeUq: uniqueIndex("seo_ops_keyword_observations_gsc_dedupe_uq")
      .on(
        table.companyId,
        table.projectId,
        table.pageId,
        table.normalizedQuery,
        table.source,
        table.dateFrom,
        table.dateTo,
        table.country,
        table.device,
      )
      .where(sql`${table.source} = 'gsc'`),
  }),
);

export const seoOpsSemanticCoreRuns = seoOps.table(
  "semantic_core_runs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    clientKey: text("client_key").notNull(),
    mcpProjectId: text("mcp_project_id").notNull(),
    mcpRunId: text("mcp_run_id").notNull(),
    layer: text("layer").notNull(),
    runMode: text("run_mode"),
    schemaVersion: text("schema_version"),
    providerVersions: jsonb("provider_versions").$type<JsonRecord>().notNull().default({}),
    artifactManifestUri: text("artifact_manifest_uri"),
    importReadiness: text("import_readiness"),
    unsafeReasons: jsonb("unsafe_reasons").$type<string[]>().notNull().default([]),
    qualityReport: jsonb("quality_report").$type<JsonRecord>().notNull().default({}),
    policyVersion: text("policy_version"),
    sourceHashes: jsonb("source_hashes").$type<unknown[]>().notNull().default([]),
    cost: jsonb("cost").$type<JsonRecord>().notNull().default({}),
    status: text("status").notNull().default("imported"),
    generatedAt: timestamp("generated_at", { withTimezone: true }),
    importedAt: timestamp("imported_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectRunUq: uniqueIndex("seo_ops_semantic_core_runs_company_project_run_uq").on(
      table.companyId,
      table.projectId,
      table.mcpRunId,
    ),
    companyProjectLayerImportedIdx: index("seo_ops_semantic_core_runs_company_project_layer_imported_idx").on(
      table.companyId,
      table.projectId,
      table.layer,
      table.importedAt,
    ),
  }),
);

export const seoOpsSemanticCoreMemberships = seoOps.table(
  "semantic_core_memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    semanticCoreRunId: uuid("semantic_core_run_id").references(() => seoOpsSemanticCoreRuns.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    clusterId: text("cluster_id"),
    layer: text("layer").notNull(),
    membership: text("membership").notNull().default("candidate"),
    parkedReason: text("parked_reason"),
    rejectedReason: text("rejected_reason"),
    domainTopicMatch: text("domain_topic_match"),
    domainTopicMatchScore: numeric("domain_topic_match_score"),
    productBindingStatus: text("product_binding_status"),
    acceptanceConfidence: numeric("acceptance_confidence"),
    reviewPriority: integer("review_priority"),
    humanReviewRequired: boolean("human_review_required").notNull().default(false),
    humanReviewReason: text("human_review_reason"),
    recommendedHumanDecision: text("recommended_human_decision"),
    evidenceSummary: text("evidence_summary"),
    policyVersion: text("policy_version"),
    localeWarningSeverity: text("locale_warning_severity"),
    acceptedLocaleWarningOverridden: boolean("accepted_locale_warning_overridden").notNull().default(false),
    localeOverrideReason: text("locale_override_reason"),
    humanDecisionApplied: boolean("human_decision_applied").notNull().default(false),
    humanDecisionBlockedReason: text("human_decision_blocked_reason"),
    searchQueryEligibility: text("search_query_eligibility"),
    queryShapeScore: numeric("query_shape_score"),
    sourcePrecisionClass: text("source_precision_class"),
    reviewDecision: text("review_decision"),
    reviewedByAgentId: uuid("reviewed_by_agent_id").references(() => agents.id),
    reviewedByUserId: text("reviewed_by_user_id"),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectKeywordLayerUq: uniqueIndex("seo_ops_semantic_core_memberships_company_project_keyword_layer_uq").on(
      table.companyId,
      table.projectId,
      table.keywordId,
      table.layer,
    ),
    companyProjectLayerMembershipIdx: index("seo_ops_semantic_core_memberships_company_project_layer_membership_idx").on(
      table.companyId,
      table.projectId,
      table.layer,
      table.membership,
    ),
  }),
);

export const seoOpsSemanticCoreReviewBatches = seoOps.table(
  "semantic_core_review_batches",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    semanticCoreRunId: uuid("semantic_core_run_id").references(() => seoOpsSemanticCoreRuns.id),
    clientKey: text("client_key").notNull(),
    mcpProjectId: text("mcp_project_id").notNull(),
    sourceRunId: text("source_run_id").notNull(),
    layer: text("layer").notNull(),
    importReadiness: text("import_readiness"),
    unsafeReasons: jsonb("unsafe_reasons").$type<string[]>().notNull().default([]),
    qualityReport: jsonb("quality_report").$type<JsonRecord>().notNull().default({}),
    policyVersion: text("policy_version"),
    acceptedCount: integer("accepted_count").notNull().default(0),
    reviewCount: integer("review_count").notNull().default(0),
    parkedCount: integer("parked_count").notNull().default(0),
    rejectedCount: integer("rejected_count").notNull().default(0),
    unresolvedReviewCount: integer("unresolved_review_count").notNull().default(0),
    warningCounts: jsonb("warning_counts").$type<JsonRecord>().notNull().default({}),
    status: text("status").notNull().default("draft"),
    mcpReviewArtifactId: text("mcp_review_artifact_id"),
    reviewedRerunId: text("reviewed_rerun_id"),
    latestImportReadinessPayload: jsonb("latest_import_readiness_payload").$type<JsonRecord>().notNull().default({}),
    blockerReasons: jsonb("blocker_reasons").$type<string[]>().notNull().default([]),
    clientReviewStatus: text("client_review_status").notNull().default("not_started"),
    clientReviewCompletedAt: timestamp("client_review_completed_at", { withTimezone: true }),
    clientReviewProcessedAt: timestamp("client_review_processed_at", { withTimezone: true }),
    clientReviewRevision: integer("client_review_revision").notNull().default(0),
    clientReviewProgress: jsonb("client_review_progress").$type<JsonRecord>().notNull().default({}),
    clientReviewSnapshot: jsonb("client_review_snapshot").$type<JsonRecord>().notNull().default({}),
    linkedIssueId: uuid("linked_issue_id").references(() => issues.id),
    createdByAgentId: uuid("created_by_agent_id").references(() => agents.id),
    createdByUserId: text("created_by_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectRunLayerUq: uniqueIndex("seo_ops_semantic_core_review_batches_run_layer_uq").on(
      table.companyId,
      table.projectId,
      table.sourceRunId,
      table.layer,
    ),
    companyProjectStatusUpdatedIdx: index("seo_ops_semantic_core_review_batches_status_updated_idx").on(
      table.companyId,
      table.projectId,
      table.status,
      table.updatedAt,
    ),
    companyIssueIdx: index("seo_ops_semantic_core_review_batches_company_issue_idx").on(
      table.companyId,
      table.linkedIssueId,
    ),
  }),
);

export const seoOpsSemanticCoreReviewItems = seoOps.table(
  "semantic_core_review_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    reviewBatchId: uuid("review_batch_id").notNull().references(() => seoOpsSemanticCoreReviewBatches.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    normalizedKeyword: text("normalized_keyword").notNull(),
    displayKeyword: text("display_keyword").notNull(),
    duplicateGroupKey: text("duplicate_group_key").notNull(),
    sourceArtifactType: text("source_artifact_type").notNull(),
    sourceRunId: text("source_run_id").notNull(),
    artifactRowPointer: text("artifact_row_pointer"),
    currentMachineMembership: text("current_machine_membership").notNull(),
    recommendedHumanDecision: text("recommended_human_decision"),
    humanDecision: text("human_decision"),
    decisionStatus: text("decision_status").notNull().default("pending"),
    productBindingStatus: text("product_binding_status"),
    domainTopicMatch: text("domain_topic_match"),
    domainTopicMatchScore: numeric("domain_topic_match_score"),
    acceptanceConfidence: numeric("acceptance_confidence"),
    reviewPriority: integer("review_priority"),
    humanReviewRequired: boolean("human_review_required").notNull().default(false),
    humanReviewReason: text("human_review_reason"),
    evidenceSummary: text("evidence_summary"),
    policyWarnings: jsonb("policy_warnings").$type<string[]>().notNull().default([]),
    localeWarningSeverity: text("locale_warning_severity"),
    acceptedLocaleWarningOverridden: boolean("accepted_locale_warning_overridden").notNull().default(false),
    localeOverrideReason: text("locale_override_reason"),
    humanDecisionApplied: boolean("human_decision_applied").notNull().default(false),
    humanDecisionBlockedReason: text("human_decision_blocked_reason"),
    searchQueryEligibility: text("search_query_eligibility"),
    queryShapeScore: numeric("query_shape_score"),
    sourcePrecisionClass: text("source_precision_class"),
    humanConnectionAssessment: text("human_connection_assessment"),
    humanConnectionNote: text("human_connection_note"),
    geoSearchVolume: integer("geo_search_volume"),
    globalSearchVolume: integer("global_search_volume"),
    latestPayload: jsonb("latest_payload").$type<JsonRecord>().notNull().default({}),
    sourceOccurrences: jsonb("source_occurrences").$type<unknown[]>().notNull().default([]),
    validationOutcome: text("validation_outcome"),
    validationReasons: jsonb("validation_reasons").$type<string[]>().notNull().default([]),
    policyVersion: text("policy_version"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    batchGroupUq: uniqueIndex("seo_ops_semantic_core_review_items_batch_group_uq").on(
      table.reviewBatchId,
      table.duplicateGroupKey,
    ),
    batchDecisionIdx: index("seo_ops_semantic_core_review_items_batch_decision_idx").on(
      table.reviewBatchId,
      table.decisionStatus,
      table.humanDecision,
    ),
    batchMembershipIdx: index("seo_ops_semantic_core_review_items_batch_membership_idx").on(
      table.reviewBatchId,
      table.currentMachineMembership,
      table.productBindingStatus,
    ),
    companyProjectKeywordIdx: index("seo_ops_semantic_core_review_items_company_keyword_idx").on(
      table.companyId,
      table.projectId,
      table.normalizedKeyword,
    ),
  }),
);

export const seoOpsSemanticCoreReviewDecisions = seoOps.table(
  "semantic_core_review_decisions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    reviewBatchId: uuid("review_batch_id").notNull().references(() => seoOpsSemanticCoreReviewBatches.id),
    reviewItemId: uuid("review_item_id").notNull().references(() => seoOpsSemanticCoreReviewItems.id),
    actorAgentId: uuid("actor_agent_id").references(() => agents.id),
    actorUserId: text("actor_user_id"),
    previousDecision: text("previous_decision"),
    newDecision: text("new_decision").notNull(),
    notes: text("notes"),
    validationOutcome: text("validation_outcome").notNull(),
    validationReasons: jsonb("validation_reasons").$type<string[]>().notNull().default([]),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    batchItemCreatedIdx: index("seo_ops_semantic_core_review_decisions_batch_item_created_idx").on(
      table.reviewBatchId,
      table.reviewItemId,
      table.createdAt,
    ),
    companyProjectCreatedIdx: index("seo_ops_semantic_core_review_decisions_company_project_created_idx").on(
      table.companyId,
      table.projectId,
      table.createdAt,
    ),
  }),
);

export const seoOpsSemanticCoreReviewGroupDecisions = seoOps.table(
  "semantic_core_review_group_decisions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    reviewBatchId: uuid("review_batch_id").notNull().references(() => seoOpsSemanticCoreReviewBatches.id),
    groupId: text("group_id").notNull(),
    canonicalReviewItemId: uuid("canonical_review_item_id").references(() => seoOpsSemanticCoreReviewItems.id),
    actorAgentId: uuid("actor_agent_id").references(() => agents.id),
    actorUserId: text("actor_user_id"),
    decision: text("decision").notNull(),
    selectedItemIds: jsonb("selected_item_ids").$type<string[]>().notNull().default([]),
    omittedItemIds: jsonb("omitted_item_ids").$type<string[]>().notNull().default([]),
    notes: text("notes"),
    rejectReason: text("reject_reason"),
    overrideReason: text("override_reason"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    batchGroupCreatedIdx: index("seo_ops_semantic_core_review_group_decisions_group_idx").on(
      table.reviewBatchId,
      table.groupId,
      table.createdAt,
    ),
    companyProjectCreatedIdx: index("seo_ops_semantic_core_review_group_decisions_company_idx").on(
      table.companyId,
      table.projectId,
      table.createdAt,
    ),
  }),
);

export const seoOpsSemanticCoreKeywordActions = seoOps.table(
  "semantic_core_keyword_actions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    normalizedKeyword: text("normalized_keyword").notNull(),
    displayKeyword: text("display_keyword").notNull(),
    action: text("action").notNull(),
    status: text("status").notNull(),
    notes: text("notes"),
    actorAgentId: uuid("actor_agent_id").references(() => agents.id),
    actorUserId: text("actor_user_id"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectKeywordCreatedIdx: index("seo_ops_semantic_core_keyword_actions_keyword_created_idx").on(
      table.companyId,
      table.projectId,
      table.normalizedKeyword,
      table.createdAt,
    ),
    companyStatusCreatedIdx: index("seo_ops_semantic_core_keyword_actions_status_created_idx").on(
      table.companyId,
      table.status,
      table.createdAt,
    ),
  }),
);

export const seoOpsClusters = seoOps.table(
  "clusters",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    externalClusterId: text("external_cluster_id"),
    label: text("label").notNull(),
    layer: text("layer"),
    intentLabel: text("intent_label"),
    status: text("status").notNull().default("candidate"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectExternalClusterUq: uniqueIndex("seo_ops_clusters_company_project_external_cluster_uq")
      .on(table.companyId, table.projectId, table.externalClusterId)
      .where(sql`${table.externalClusterId} is not null`),
    companyProjectLayerStatusIdx: index("seo_ops_clusters_company_project_layer_status_idx").on(
      table.companyId,
      table.projectId,
      table.layer,
      table.status,
    ),
  }),
);

export const seoOpsSemanticSegments = seoOps.table(
  "semantic_segments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    semanticCoreRunId: uuid("semantic_core_run_id").references(() => seoOpsSemanticCoreRuns.id),
    externalSegmentId: text("external_segment_id"),
    segmentType: text("segment_type").notNull(),
    label: text("label"),
    layer: text("layer"),
    intentLabel: text("intent_label"),
    ownerTypeFinal: text("owner_type_final"),
    productBindings: jsonb("product_bindings").$type<unknown[]>().notNull().default([]),
    primaryKeywords: jsonb("primary_keywords").$type<unknown[]>().notNull().default([]),
    clusterIds: jsonb("cluster_ids").$type<unknown[]>().notNull().default([]),
    evidenceSummary: jsonb("evidence_summary").$type<JsonRecord>().notNull().default({}),
    status: text("status").notNull().default("candidate"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectExternalSegmentUq: uniqueIndex("seo_ops_semantic_segments_company_project_external_segment_uq")
      .on(table.companyId, table.projectId, table.externalSegmentId)
      .where(sql`${table.externalSegmentId} is not null`),
    companyProjectSegmentTypeStatusIdx: index("seo_ops_semantic_segments_company_project_type_status_idx").on(
      table.companyId,
      table.projectId,
      table.segmentType,
      table.status,
    ),
    companyProjectLayerIntentIdx: index("seo_ops_semantic_segments_company_project_layer_intent_idx").on(
      table.companyId,
      table.projectId,
      table.layer,
      table.intentLabel,
    ),
  }),
);

export const seoOpsSemanticSegmentKeywords = seoOps.table(
  "semantic_segment_keywords",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    semanticSegmentId: uuid("semantic_segment_id").notNull().references(() => seoOpsSemanticSegments.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    relationshipType: text("relationship_type").notNull().default("member"),
    source: text("source"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectSegmentKeywordTypeUq: uniqueIndex("seo_ops_semantic_segment_keywords_segment_keyword_type_uq").on(
      table.companyId,
      table.projectId,
      table.semanticSegmentId,
      table.keywordId,
      table.relationshipType,
    ),
    companyProjectKeywordIdx: index("seo_ops_semantic_segment_keywords_company_project_keyword_idx").on(
      table.companyId,
      table.projectId,
      table.keywordId,
    ),
  }),
);

export const seoOpsKeywordClusterMemberships = seoOps.table(
  "keyword_cluster_memberships",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    clusterId: uuid("cluster_id").notNull().references(() => seoOpsClusters.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    membershipStatus: text("membership_status").notNull().default("candidate"),
    source: text("source"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectClusterKeywordUq: uniqueIndex("seo_ops_keyword_cluster_memberships_cluster_keyword_uq").on(
      table.companyId,
      table.projectId,
      table.clusterId,
      table.keywordId,
    ),
    companyProjectKeywordIdx: index("seo_ops_keyword_cluster_memberships_company_project_keyword_idx").on(
      table.companyId,
      table.projectId,
      table.keywordId,
    ),
  }),
);

export const seoOpsPageKeywordTargets = seoOps.table(
  "page_keyword_targets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    projectPageId: uuid("project_page_id").notNull().references(() => seoOpsProjectPages.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    targetType: text("target_type").notNull(),
    status: text("status").notNull().default("candidate"),
    tier: text("tier").notNull().default("tier_3"),
    source: text("source").notNull(),
    priority: integer("priority").notNull().default(100),
    isPrimary: boolean("is_primary").notNull().default(false),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
    parkedReason: text("parked_reason"),
    rejectedReason: text("rejected_reason"),
    notes: text("notes"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectPageKeywordTypeUq: uniqueIndex("seo_ops_page_keyword_targets_page_keyword_type_uq").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.keywordId,
      table.targetType,
    ),
    acceptedPrimaryUq: uniqueIndex("seo_ops_page_keyword_targets_accepted_primary_uq")
      .on(table.companyId, table.projectId, table.projectPageId)
      .where(sql`${table.isPrimary} = true and ${table.status} = 'accepted'`),
    companyProjectTierStatusIdx: index("seo_ops_page_keyword_targets_company_project_tier_status_idx").on(
      table.companyId,
      table.projectId,
      table.tier,
      table.status,
    ),
  }),
);

export const seoOpsRankTrackingPolicies = seoOps.table(
  "rank_tracking_policies",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    scopeLevel: text("scope_level").notNull(),
    tier: text("tier").notNull(),
    provider: text("provider").notNull(),
    searchEngine: text("search_engine").notNull().default("google"),
    geo: text("geo").notNull(),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context").notNull().default("desktop"),
    frequency: text("frequency").notNull(),
    intervalDays: integer("interval_days"),
    scheduleCron: text("schedule_cron"),
    jitterMinutes: integer("jitter_minutes").notNull().default(0),
    maxKeywords: integer("max_keywords"),
    maxCostCentsPerPeriod: integer("max_cost_cents_per_period"),
    escalationThreshold: jsonb("escalation_threshold").$type<JsonRecord>().notNull().default({}),
    temporaryWatchDurationDays: integer("temporary_watch_duration_days"),
    stopConditions: jsonb("stop_conditions").$type<JsonRecord>().notNull().default({}),
    status: text("status").notNull().default("active"),
    identityKey: text("identity_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_rank_tracking_policies_identity_uq").on(table.identityKey),
    companyProjectStatusIdx: index("seo_ops_rank_tracking_policies_company_project_status_idx").on(
      table.companyId,
      table.projectId,
      table.status,
    ),
  }),
);

export const seoOpsRankTrackingTargets = seoOps.table(
  "rank_tracking_targets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    pageKeywordTargetId: uuid("page_keyword_target_id").references(() => seoOpsPageKeywordTargets.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    policyId: uuid("policy_id").references(() => seoOpsRankTrackingPolicies.id),
    provider: text("provider").notNull(),
    searchEngine: text("search_engine").notNull().default("google"),
    geo: text("geo").notNull(),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context").notNull(),
    trackingStatus: text("tracking_status").notNull().default("active"),
    nextCheckAt: timestamp("next_check_at", { withTimezone: true }),
    lastCheckAt: timestamp("last_check_at", { withTimezone: true }),
    temporaryWatchUntil: timestamp("temporary_watch_until", { withTimezone: true }),
    identityKey: text("identity_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_rank_tracking_targets_identity_uq").on(table.identityKey),
    trackingNextCheckIdx: index("seo_ops_rank_tracking_targets_tracking_next_check_idx").on(
      table.trackingStatus,
      table.nextCheckAt,
    ),
    companyProjectTrackingIdx: index("seo_ops_rank_tracking_targets_company_project_tracking_idx").on(
      table.companyId,
      table.projectId,
      table.trackingStatus,
    ),
  }),
);

export const seoOpsPageSerpTargets = seoOps.table(
  "page_serp_targets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    projectPageId: uuid("project_page_id").notNull().references(() => seoOpsProjectPages.id),
    pageKeywordTargetId: uuid("page_keyword_target_id").references(() => seoOpsPageKeywordTargets.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    policyId: uuid("policy_id").references(() => seoOpsRankTrackingPolicies.id),
    provider: text("provider").notNull().default("serper"),
    searchEngine: text("search_engine").notNull().default("google"),
    geo: text("geo").notNull(),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context").notNull().default("desktop"),
    trackingStatus: text("tracking_status").notNull().default("active"),
    nextCheckAt: timestamp("next_check_at", { withTimezone: true }),
    lastCheckAt: timestamp("last_check_at", { withTimezone: true }),
    temporaryWatchUntil: timestamp("temporary_watch_until", { withTimezone: true }),
    identityKey: text("identity_key").notNull(),
    settings: jsonb("settings").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_page_serp_targets_identity_uq").on(table.identityKey),
    pageKeywordContextUq: uniqueIndex("seo_ops_page_serp_targets_page_keyword_context_uq").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.keywordId,
      table.provider,
      table.searchEngine,
      table.geo,
      table.languageCode,
      table.deviceContext,
    ),
    trackingNextCheckIdx: index("seo_ops_page_serp_targets_tracking_next_check_idx").on(
      table.trackingStatus,
      table.nextCheckAt,
    ),
    companyProjectPageTrackingIdx: index("seo_ops_page_serp_targets_company_project_page_tracking_idx").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.trackingStatus,
    ),
  }),
);

export const seoOpsSerpSnapshots = seoOps.table(
  "serp_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    rankTrackingTargetId: uuid("rank_tracking_target_id").references(() => seoOpsRankTrackingTargets.id),
    pageSerpTargetId: uuid("page_serp_target_id").references(() => seoOpsPageSerpTargets.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    provider: text("provider").notNull().default("serper"),
    searchEngine: text("search_engine").notNull().default("google"),
    geo: text("geo").notNull(),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context").notNull().default("desktop"),
    requestedQuery: text("requested_query").notNull(),
    requestedNumResults: integer("requested_num_results"),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    snapshotDate: date("snapshot_date").notNull(),
    status: text("status").notNull().default("ok"),
    requestFingerprint: text("request_fingerprint").notNull(),
    rawPayload: jsonb("raw_payload").$type<JsonRecord>().notNull().default({}),
    pluginJobRunId: uuid("plugin_job_run_id").references(() => pluginJobRuns.id),
    heartbeatRunId: uuid("heartbeat_run_id").references(() => heartbeatRuns.id),
    costEventId: uuid("cost_event_id").references(() => costEvents.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    requestFingerprintUq: uniqueIndex("seo_ops_serp_snapshots_request_fingerprint_uq").on(table.requestFingerprint),
    companyProjectSnapshotDateIdx: index("seo_ops_serp_snapshots_company_project_date_idx").on(
      table.companyId,
      table.projectId,
      table.snapshotDate,
    ),
    companyProjectKeywordObservedIdx: index("seo_ops_serp_snapshots_company_project_keyword_observed_idx").on(
      table.companyId,
      table.projectId,
      table.keywordId,
      table.observedAt,
    ),
    contextDateIdx: index("seo_ops_serp_snapshots_context_date_idx").on(
      table.companyId,
      table.projectId,
      table.provider,
      table.searchEngine,
      table.geo,
      table.languageCode,
      table.deviceContext,
      table.snapshotDate,
    ),
  }),
);

export const seoOpsSerpSnapshotResults = seoOps.table(
  "serp_snapshot_results",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    serpSnapshotId: uuid("serp_snapshot_id").notNull().references(() => seoOpsSerpSnapshots.id),
    resultPosition: integer("result_position").notNull(),
    resultType: text("result_type").notNull().default("organic"),
    resultUrl: text("result_url"),
    resultUrlNormalized: text("result_url_normalized"),
    resultDomain: text("result_domain"),
    title: text("title"),
    snippet: text("snippet"),
    isOwnedDomain: boolean("is_owned_domain").notNull().default(false),
    matchedSiteId: uuid("matched_site_id").references(() => seoOpsSites.id),
    matchedPageId: uuid("matched_page_id").references(() => seoOpsPages.id),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    snapshotPositionTypeUq: uniqueIndex("seo_ops_serp_snapshot_results_snapshot_position_type_uq").on(
      table.serpSnapshotId,
      table.resultPosition,
      table.resultType,
    ),
    companyProjectDomainIdx: index("seo_ops_serp_snapshot_results_company_project_domain_idx").on(
      table.companyId,
      table.projectId,
      table.resultDomain,
    ),
    companyProjectMatchedPageIdx: index("seo_ops_serp_snapshot_results_company_project_matched_page_idx").on(
      table.companyId,
      table.projectId,
      table.matchedPageId,
      table.serpSnapshotId,
    ),
  }),
);

export const seoOpsSerpRankObservations = seoOps.table(
  "serp_rank_observations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    pageKeywordTargetId: uuid("page_keyword_target_id").references(() => seoOpsPageKeywordTargets.id),
    rankTrackingTargetId: uuid("rank_tracking_target_id").references(() => seoOpsRankTrackingTargets.id),
    pageSerpTargetId: uuid("page_serp_target_id").references(() => seoOpsPageSerpTargets.id),
    keywordId: uuid("keyword_id").notNull().references(() => seoOpsKeywords.id),
    serpSnapshotId: uuid("serp_snapshot_id").references(() => seoOpsSerpSnapshots.id),
    provider: text("provider").notNull().default("serper"),
    searchEngine: text("search_engine").notNull().default("google"),
    geo: text("geo").notNull(),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context").notNull(),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    snapshotDate: date("snapshot_date").notNull(),
    rankPosition: numeric("rank_position"),
    rankUrl: text("rank_url"),
    rankUrlNormalized: text("rank_url_normalized"),
    rankResultType: text("rank_result_type"),
    ownedResultCount: integer("owned_result_count").notNull().default(0),
    bestOwnedPosition: numeric("best_owned_position"),
    visibilityState: text("visibility_state").notNull().default("observed"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    identityKey: text("identity_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_serp_rank_observations_identity_uq").on(table.identityKey),
    companyProjectKeywordObservedIdx: index("seo_ops_serp_rank_observations_company_project_keyword_observed_idx").on(
      table.companyId,
      table.projectId,
      table.keywordId,
      table.observedAt,
    ),
    companyProjectPageObservedIdx: index("seo_ops_serp_rank_observations_company_project_page_observed_idx").on(
      table.companyId,
      table.projectPageId,
      table.observedAt,
    ),
    companyProjectVisibilityDateIdx: index("seo_ops_serp_rank_observations_company_project_visibility_date_idx").on(
      table.companyId,
      table.projectId,
      table.visibilityState,
      table.snapshotDate,
    ),
  }),
);

export const seoOpsPerformanceSnapshots = seoOps.table(
  "performance_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    pageKeywordTargetId: uuid("page_keyword_target_id").references(() => seoOpsPageKeywordTargets.id),
    snapshotDate: date("snapshot_date").notNull(),
    source: text("source").notNull(),
    clicks: integer("clicks"),
    impressions: integer("impressions"),
    ctr: numeric("ctr"),
    averagePosition: numeric("average_position"),
    provider: text("provider"),
    classification: text("classification"),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectSnapshotDateIdx: index("seo_ops_performance_snapshots_company_project_date_idx").on(
      table.companyId,
      table.projectId,
      table.snapshotDate,
    ),
    companyProjectPageSnapshotDateIdx: index("seo_ops_performance_snapshots_company_project_page_date_idx").on(
      table.companyId,
      table.projectPageId,
      table.snapshotDate,
    ),
    companyKeywordSnapshotDateIdx: index("seo_ops_performance_snapshots_company_keyword_date_idx").on(
      table.companyId,
      table.keywordId,
      table.snapshotDate,
    ),
  }),
);

export const seoOpsMetricWindows = seoOps.table(
  "metric_windows",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    pageSerpTargetId: uuid("page_serp_target_id").references(() => seoOpsPageSerpTargets.id),
    windowType: text("window_type").notNull(),
    source: text("source").notNull(),
    dateFrom: date("date_from").notNull(),
    dateTo: date("date_to").notNull(),
    sourceQueryParams: jsonb("source_query_params").$type<JsonRecord>().notNull().default({}),
    clicks: integer("clicks"),
    impressions: integer("impressions"),
    ctr: numeric("ctr"),
    averagePosition: numeric("average_position"),
    bestOwnedPosition: numeric("best_owned_position"),
    ownedResultCount: integer("owned_result_count"),
    evidenceRefs: jsonb("evidence_refs").$type<unknown[]>().notNull().default([]),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    pageWindowSourceUq: uniqueIndex("seo_ops_metric_windows_page_window_source_uq").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.keywordId,
      table.windowType,
      table.source,
      table.dateFrom,
      table.dateTo,
    ),
    companyProjectWindowIdx: index("seo_ops_metric_windows_company_project_window_idx").on(
      table.companyId,
      table.projectId,
      table.windowType,
      table.dateTo,
    ),
  }),
);

export const seoOpsSeoDecisions = seoOps.table(
  "seo_decisions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    pageSerpTargetId: uuid("page_serp_target_id").references(() => seoOpsPageSerpTargets.id),
    decisionType: text("decision_type").notNull(),
    decisionStatus: text("decision_status").notNull(),
    decisionReason: text("decision_reason").notNull(),
    decisionWindowStart: date("decision_window_start").notNull(),
    decisionWindowEnd: date("decision_window_end").notNull(),
    baselineWindowId: uuid("baseline_window_id").references(() => seoOpsMetricWindows.id),
    postActionWindowId: uuid("post_action_window_id").references(() => seoOpsMetricWindows.id),
    comparisonWindowId: uuid("comparison_window_id").references(() => seoOpsMetricWindows.id),
    recentActionEventIds: jsonb("recent_action_event_ids").$type<string[]>().notNull().default([]),
    policySnapshot: jsonb("policy_snapshot").$type<JsonRecord>().notNull().default({}),
    evidenceRefs: jsonb("evidence_refs").$type<unknown[]>().notNull().default([]),
    openedIssueId: uuid("opened_issue_id").references(() => issues.id),
    actorAgentId: uuid("actor_agent_id").references(() => agents.id),
    actorUserId: text("actor_user_id"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectPageCreatedIdx: index("seo_ops_seo_decisions_company_project_page_created_idx").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.createdAt,
    ),
    companyProjectStatusCreatedIdx: index("seo_ops_seo_decisions_company_project_status_created_idx").on(
      table.companyId,
      table.projectId,
      table.decisionStatus,
      table.createdAt,
    ),
  }),
);

export const seoOpsIndexingInspectionSnapshots = seoOps.table(
  "indexing_inspection_snapshots",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    pageId: uuid("page_id").references(() => seoOpsPages.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    discoveryRunId: uuid("discovery_run_id").references(() => seoOpsDiscoveryRuns.id),
    url: text("url").notNull(),
    urlNormalized: text("url_normalized").notNull(),
    checkedAt: timestamp("checked_at", { withTimezone: true }).notNull().defaultNow(),
    provider: text("provider").notNull().default("google_search_console"),
    verdict: text("verdict"),
    coverageState: text("coverage_state"),
    indexingState: text("indexing_state"),
    pageFetchState: text("page_fetch_state"),
    robotsTxtState: text("robots_txt_state"),
    googleCanonical: text("google_canonical"),
    userCanonical: text("user_canonical"),
    lastCrawlTime: timestamp("last_crawl_time", { withTimezone: true }),
    inspectionResultLink: text("inspection_result_link"),
    cacheHit: boolean("cache_hit").notNull().default(false),
    apiCallMade: boolean("api_call_made").notNull().default(false),
    quotaUnits: numeric("quota_units"),
    normalizedPayload: jsonb("normalized_payload").$type<JsonRecord>().notNull().default({}),
    rawPayloadRef: text("raw_payload_ref"),
    rawPayloadHash: text("raw_payload_hash"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    discoveryUrlUq: uniqueIndex("seo_ops_indexing_snapshots_discovery_url_uq").on(
      table.companyId,
      table.discoveryRunId,
      table.urlNormalized,
    ),
    companySiteCheckedIdx: index("seo_ops_indexing_snapshots_company_site_checked_idx").on(
      table.companyId,
      table.siteId,
      table.checkedAt,
    ),
    companyPageCheckedIdx: index("seo_ops_indexing_snapshots_company_page_checked_idx").on(
      table.companyId,
      table.pageId,
      table.checkedAt,
    ),
    projectPageCheckedIdx: index("seo_ops_indexing_snapshots_project_page_checked_idx").on(
      table.projectPageId,
      table.checkedAt,
    ),
    verdictIdx: index("seo_ops_indexing_snapshots_verdict_idx").on(
      table.companyId,
      table.verdict,
      table.coverageState,
    ),
  }),
);

export const seoOpsPageFindings = seoOps.table(
  "page_findings",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").references(() => projects.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    pageId: uuid("page_id").references(() => seoOpsPages.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    source: text("source").notNull(),
    findingType: text("finding_type").notNull(),
    problemClass: text("problem_class").notNull(),
    severity: text("severity").notNull().default("medium"),
    status: text("status").notNull().default("open"),
    firstSeenAt: timestamp("first_seen_at", { withTimezone: true }).notNull().defaultNow(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    fingerprint: text("fingerprint").notNull(),
    latestSnapshotId: uuid("latest_snapshot_id").references(() => seoOpsIndexingInspectionSnapshots.id),
    linkedIssueId: uuid("linked_issue_id").references(() => issues.id),
    evidenceSummary: text("evidence_summary"),
    evidenceRefs: jsonb("evidence_refs").$type<JsonRecord>().notNull().default({}),
    policySnapshot: jsonb("policy_snapshot").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyFingerprintUq: uniqueIndex("seo_ops_page_findings_company_fingerprint_uq").on(
      table.companyId,
      table.fingerprint,
    ),
    companyStatusSeverityIdx: index("seo_ops_page_findings_company_status_severity_idx").on(
      table.companyId,
      table.status,
      table.severity,
    ),
    projectPageStatusIdx: index("seo_ops_page_findings_project_page_status_idx").on(
      table.projectPageId,
      table.status,
    ),
    companyProblemIdx: index("seo_ops_page_findings_company_problem_idx").on(
      table.companyId,
      table.findingType,
      table.problemClass,
      table.status,
    ),
    linkedIssueIdx: index("seo_ops_page_findings_linked_issue_idx").on(table.linkedIssueId),
  }),
);

export const seoOpsNewPageOpportunities = seoOps.table(
  "new_page_opportunities",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    sourceObservationId: uuid("source_observation_id").references(() => seoOpsKeywordObservations.id),
    currentPageId: uuid("current_page_id").references(() => seoOpsPages.id),
    currentProjectPageId: uuid("current_project_page_id").references(() => seoOpsProjectPages.id),
    landingFitState: text("landing_fit_state").notNull(),
    intentLabel: text("intent_label"),
    audienceRelevance: text("audience_relevance"),
    topicalAuthorityFit: text("topical_authority_fit"),
    productRelation: text("product_relation"),
    businessValue: text("business_value"),
    proposedPageType: text("proposed_page_type"),
    suggestedPriority: integer("suggested_priority").notNull().default(100),
    validationStatus: text("validation_status").notNull().default("candidate"),
    decision: text("decision"),
    linkedIssueId: uuid("linked_issue_id").references(() => issues.id),
    payload: jsonb("payload").$type<JsonRecord>().notNull().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectValidationPriorityIdx: index("seo_ops_new_page_opportunities_company_project_validation_priority_idx").on(
      table.companyId,
      table.projectId,
      table.validationStatus,
      table.suggestedPriority,
    ),
    companyKeywordIdx: index("seo_ops_new_page_opportunities_company_keyword_idx").on(
      table.companyId,
      table.keywordId,
    ),
  }),
);

export const seoOpsAiVisibilityTargets = seoOps.table(
  "ai_visibility_targets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    promptText: text("prompt_text").notNull(),
    promptNormalized: text("prompt_normalized").notNull(),
    answerEngine: text("answer_engine").notNull(),
    engineVariant: text("engine_variant"),
    geo: text("geo"),
    languageCode: text("language_code").notNull(),
    deviceContext: text("device_context"),
    targetDomain: text("target_domain"),
    targetUrl: text("target_url"),
    frequency: text("frequency").notNull(),
    intervalDays: integer("interval_days"),
    nextCheckAt: timestamp("next_check_at", { withTimezone: true }),
    lastCheckAt: timestamp("last_check_at", { withTimezone: true }),
    trackingStatus: text("tracking_status").notNull().default("active"),
    priority: integer("priority").notNull().default(100),
    settings: jsonb("settings").$type<JsonRecord>().notNull().default({}),
    identityKey: text("identity_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_ai_visibility_targets_identity_uq").on(table.identityKey),
    trackingNextCheckIdx: index("seo_ops_ai_visibility_targets_tracking_next_check_idx").on(
      table.trackingStatus,
      table.nextCheckAt,
    ),
    companyProjectEngineTrackingIdx: index("seo_ops_ai_visibility_targets_company_project_engine_tracking_idx").on(
      table.companyId,
      table.projectId,
      table.answerEngine,
      table.trackingStatus,
    ),
  }),
);

export const seoOpsAiVisibilityObservations = seoOps.table(
  "ai_visibility_observations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    siteId: uuid("site_id").references(() => seoOpsSites.id),
    aiVisibilityTargetId: uuid("ai_visibility_target_id").notNull().references(() => seoOpsAiVisibilityTargets.id),
    keywordId: uuid("keyword_id").references(() => seoOpsKeywords.id),
    projectPageId: uuid("project_page_id").references(() => seoOpsProjectPages.id),
    answerEngine: text("answer_engine").notNull(),
    engineVariant: text("engine_variant"),
    geo: text("geo"),
    languageCode: text("language_code").notNull(),
    observedAt: timestamp("observed_at", { withTimezone: true }).notNull(),
    snapshotDate: date("snapshot_date").notNull(),
    promptText: text("prompt_text").notNull(),
    answerHash: text("answer_hash").notNull(),
    targetDomainMentioned: boolean("target_domain_mentioned").notNull().default(false),
    brandMentioned: boolean("brand_mentioned").notNull().default(false),
    targetUrlMentioned: boolean("target_url_mentioned").notNull().default(false),
    mentionedUrls: jsonb("mentioned_urls").$type<unknown[]>().notNull().default([]),
    mentionRank: integer("mention_rank"),
    visibilityScore: numeric("visibility_score"),
    sentimentLabel: text("sentiment_label"),
    citationCount: integer("citation_count"),
    rawAnswerExcerpt: text("raw_answer_excerpt"),
    rawPayload: jsonb("raw_payload").$type<JsonRecord>().notNull().default({}),
    provider: text("provider"),
    pluginJobRunId: uuid("plugin_job_run_id").references(() => pluginJobRuns.id),
    heartbeatRunId: uuid("heartbeat_run_id").references(() => heartbeatRuns.id),
    costEventId: uuid("cost_event_id").references(() => costEvents.id),
    identityKey: text("identity_key").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    identityUq: uniqueIndex("seo_ops_ai_visibility_observations_identity_uq").on(table.identityKey),
    companyProjectEngineSnapshotIdx: index("seo_ops_ai_visibility_observations_company_project_engine_snapshot_idx").on(
      table.companyId,
      table.projectId,
      table.answerEngine,
      table.snapshotDate,
    ),
    companyProjectDomainMentionedIdx: index("seo_ops_ai_visibility_observations_company_project_domain_mentioned_idx").on(
      table.companyId,
      table.projectId,
      table.targetDomainMentioned,
      table.snapshotDate,
    ),
    companyProjectPageSnapshotIdx: index("seo_ops_ai_visibility_observations_company_project_page_snapshot_idx").on(
      table.companyId,
      table.projectPageId,
      table.snapshotDate,
    ),
  }),
);

export const seoOpsPageActionEvents = seoOps.table(
  "page_action_events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    projectId: uuid("project_id").notNull().references(() => projects.id),
    projectPageId: uuid("project_page_id").notNull().references(() => seoOpsProjectPages.id),
    issueId: uuid("issue_id").references(() => issues.id),
    agentId: uuid("agent_id").references(() => agents.id),
    eventType: text("event_type").notNull(),
    eventPayload: jsonb("event_payload").$type<JsonRecord>().notNull().default({}),
    affectedKeywordIds: jsonb("affected_keyword_ids").$type<string[]>().notNull().default([]),
    expectedEffect: text("expected_effect"),
    cooldownUntil: timestamp("cooldown_until", { withTimezone: true }),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyProjectPageOccurredIdx: index("seo_ops_page_action_events_company_project_page_occurred_idx").on(
      table.companyId,
      table.projectId,
      table.projectPageId,
      table.occurredAt,
    ),
    companyIssueIdx: index("seo_ops_page_action_events_company_issue_idx").on(table.companyId, table.issueId),
  }),
);

export const seoOpsScopeConflicts = seoOps.table(
  "scope_conflicts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    companyId: uuid("company_id").notNull().references(() => companies.id),
    siteId: uuid("site_id").notNull().references(() => seoOpsSites.id),
    pageId: uuid("page_id").notNull().references(() => seoOpsPages.id),
    conflictType: text("conflict_type").notNull(),
    conflictingProjectPageIds: jsonb("conflicting_project_page_ids").$type<string[]>().notNull().default([]),
    status: text("status").notNull().default("open"),
    resolution: text("resolution"),
    resolvedByAgentId: uuid("resolved_by_agent_id").references(() => agents.id),
    resolvedByUserId: text("resolved_by_user_id"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    linkedIssueId: uuid("linked_issue_id").references(() => issues.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    companyStatusCreatedIdx: index("seo_ops_scope_conflicts_company_status_created_idx").on(
      table.companyId,
      table.status,
      table.createdAt,
    ),
    companySitePageIdx: index("seo_ops_scope_conflicts_company_site_page_idx").on(
      table.companyId,
      table.siteId,
      table.pageId,
    ),
  }),
);
